// App-managed runtime env for the falcon-mcp sidecar.
//
// The sidecar needs FALCON_CLIENT_ID / FALCON_CLIENT_SECRET, and the app needs
// to know whether credentials exist at all (server.js only advertises the MCP
// server when they do). Without this file those are two separate places to put
// the same secret — credentials in .env alone leave the app refusing to
// advertise the server, and credentials in the secret store alone leave the
// sidecar unable to authenticate. Either way Falcon silently does nothing.
//
// So the secret store is the single source of truth and the app renders this
// file for the sidecar to read via compose `env_file` (required:false), exactly
// as graphiti/runtime/embedder.env works for the memory stack. Changes apply on
// the next `docker compose --profile falcon up -d`.
//
// The file holds a live API secret, so it is written 0600 and gitignored.
import fs from 'node:fs';
import path from 'node:path';

export const FALCON_RUNTIME_ENV_PATH = process.env.EH_FALCON_ENV_PATH
  || path.resolve(import.meta.dirname, '..', 'falcon', 'runtime', 'falcon.env');

// A CrowdStrike client id/secret is an opaque token; a base URL is a plain
// https origin. Anything carrying a newline, quote, or whitespace could break
// out of KEY=value into a second assignment, so such a value is dropped rather
// than escaped — a credential that shape is malformed, not merely awkward.
const SAFE_VALUE = /^[A-Za-z0-9._:/?=&~+-]+$/;

const safe = (v) => {
  const s = typeof v === 'string' ? v.trim() : '';
  return s && SAFE_VALUE.test(s) ? s : '';
};

/** Render the sidecar env file. Only non-empty, safe values are emitted. */
export function renderFalconRuntimeEnv({ clientId, clientSecret, baseUrl } = {}) {
  const lines = [
    '# Generated by the app from the secret store — do not edit by hand.',
    '# Rewritten whenever Falcon settings or credentials are saved.',
  ];
  const id = safe(clientId);
  const secret = safe(clientSecret);
  const base = safe(baseUrl);
  if (id) lines.push(`FALCON_CLIENT_ID=${id}`);
  if (secret) lines.push(`FALCON_CLIENT_SECRET=${secret}`);
  if (base) lines.push(`FALCON_BASE_URL=${base}`);
  return `${lines.join('\n')}\n`;
}

/**
 * Write the sidecar env file. Best-effort: a failure here must never take the
 * app down, and the consequence is a Falcon sidecar that cannot authenticate —
 * which is visible, not silent, because the app also declines to advertise the
 * server when it has no credentials.
 */
export function writeFalconRuntimeEnv(creds = {}, file = FALCON_RUNTIME_ENV_PATH) {
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, renderFalconRuntimeEnv(creds), { mode: 0o600 });
    // writeFileSync only applies mode on create, so an existing file keeps its
    // old permissions unless chmod'd explicitly.
    fs.chmodSync(file, 0o600);
    return true;
  } catch (err) {
    console.warn(`[falcon-runtime-env] could not write ${file}: ${err.message}`);
    return false;
  }
}
